### ISSUE TITLE
Bump msw to new API

### ISSUE THREAD

**Issue by szilarddoro** [nhost/nhost#2040]
MSW doesn't support Node.js v18 yet so the tests are still running on Node.js v16. Bump the version in the CI once MSW adds Node.js v18 support.

Please refer to this issue:
https://github.com/mswjs/msw/issues/1388
```[tasklist]
### Tasks
- [ ] Bump the version in the CI
- [ ] Bump the version in the Dockerfile
- [ ] Update DEVELOPERS.md to indicate that only Node.js v18 is supported
```

**Comment by dbarrosop** [comment]
Does it makes sense to use `next` as this comment describes? https://github.com/mswjs/msw/issues/1388#issuecomment-1545693391

**Comment by szilarddoro** [comment]
We can give it a shot, yes.

**Comment by szilarddoro** [comment]
I tried it but the tests will break after upgrading to `msw@next` so I'd say let's wait for a proper release or a better release candidate.

**Comment by onehassan** [comment]
It seems that there are breaking changes to we write tests

https://github.com/mswjs/msw/blob/feat/standard-api/MIGRATING.md

Currently migrating to use the new API
