### ISSUE TITLE
minor fixes to dashboard -> run

### ISSUE THREAD

**Issue by dbarrosop** [nhost/nhost#2159]
```[tasklist]
### Tasks
- [x] env var values should support multiline values and resizing input box
- [ ] make the whole editor bigger?
- [x] in the logs section, when querying logs, prepend `run-` to the name
```
