### ISSUE TITLE
deprecate old backend url

### ISSUE THREAD

**Issue by dbarrosop** [nhost/nhost#2289]
Announcement was already made long ago but some people raised concerns and we decided to delay it. We need to do this.

```[tasklist]
### Tasks
- [x] agree on a date (Dec 1st)
- [x] make announcement
- [ ] https://github.com/nhost/nhost/issues/2340
- [ ] https://github.com/nhost/nhost/issues/2361
- [ ] https://github.com/nhost/be/issues/507
- [ ] https://github.com/nhost/infrastructure/issues/511
- [ ] https://github.com/nhost/nhost/issues/2339
- [ ] https://github.com/nhost/nhost-dart/issues/118
- [ ] https://github.com/nhost/infrastructure/issues/512
- [ ] https://github.com/nhost/be/pull/550
- [x] remove BACKEND_URL from be repo
```

**Comment by dbarrosop** [comment]
I basically looked at all apps with desired_state == LIVE and using some oauth mechanism and set providers_updated = true to the REST. Now we have only 24 apps with providers_updated = false.

**Comment by dbarrosop** [comment]
https://github.com/nhost/nhost-dart/issues/107#issuecomment-1751652021
