### ISSUE TITLE
healthz / alive endpoint for run services

### ISSUE THREAD

**Issue by kelkes** [nhost/nhost#2385]
**Is your feature request related to a problem? Please describe.**
The trigger was as follows. One of my background workers stopped checking in with my monitoring solution. the service didn't crash, but it just stopped working. While that is clearly something I should fix, it would be nice to have an alive route who would check periodically and on failure kills the container and restarts it. I was out of the office when that happened and rebooting the service from my smartphone was pita.

**Describe the solution you'd like**
Add a toggle to enable healtz/alive checks for run services. If they don't respond as expected, add some kind of notification and reboot them (including some back-off mechanism).

**Describe alternatives you've considered**
API to reboot run services. This would enable me to build that on my own.

```[tasklist]
### Tasks
- [x] https://github.com/nhost/nhost/issues/2411
- [ ] https://github.com/nhost/nhost/issues/2412
- [ ] https://github.com/nhost/nhost/issues/2413
- [ ] https://github.com/nhost/nhost/issues/2410
```

**Comment by kelkes** [comment]
It's for scenarios like this:

<img width="634" alt="SCR-20231128-hsol" src="https://github.com/nhost/nhost/assets/204445/f1663223-5a24-4421-b5d2-04750fd70fd2">

That's one of my run services. It stopped checking in at 8:00... i have no idea why. No log, no crash, no error ... nothing. Memory/CPU consumption were low according to Grafana. Of course, it's not a nhost problem and I need to fix this, but meanwhile, an automatic reboot could lower my stress level and give me the peace to figure this out.

**Comment by dbarrosop** [comment]
Agreed, we have this issue scheduled for December so soon :)

**Comment by kelkes** [comment]
🥳

**Comment by NesManrique** [comment]
@kelkes not done yet, just the backend part but the rest should come soon 😄
