### ISSUE TITLE
implement elevate methods/hooks

### ISSUE THREAD

**Issue by dbarrosop** [nhost/nhost#2394]
See https://github.com/nhost/hasura-auth/pull/451
```[tasklist]
### Tasks
- [ ] https://github.com/nhost/hasura-auth/pull/462
- [ ] https://github.com/nhost/be/pull/587
- [ ] https://github.com/nhost/cli/pull/828
- [ ] https://github.com/nhost/nhost/pull/2519
- [ ] https://github.com/nhost/nhost/pull/2521
```
