### ISSUE TITLE
social connect

### ISSUE THREAD

**Issue by dbarrosop** [nhost/nhost#2503]
```[tasklist]
### Tasks
- [ ] https://github.com/nhost/hasura-auth/pull/459
- [ ] https://github.com/nhost/nhost/issues/2581
- [ ] https://github.com/nhost/nhost/issues/2582
- [x] blog post
- [ ] docs
```
