### ISSUE TITLE
encrypted volumes

### ISSUE THREAD

**Issue by dbarrosop** [nhost/nhost#2781]
```[tasklist]
### Tasks
- [ ] https://github.com/nhost/be/pull/830
- [ ] https://github.com/nhost/nhost/issues/3050
- [ ] https://github.com/nhost/nhost/pull/3142
```
