### ISSUE TITLE
Postgres extension : pg_repack (used for partitionning)

### ISSUE THREAD

**Issue by quentin-decre** [nhost/nhost#2942]
**Is your feature request related to a problem? Please describe.**
I want to partition some table to improve performances. But partitionning existing tables means create another table (with columns, constraints, triggers, indexes) + paritioning informations, then migrate the data, then remove the old table, then rename the new table.
A bit of a hassle + significant downtime.

**Describe the solution you'd like**
pg_repack (https://github.com/reorg/pg_repack) helps reorganize tables in PostgreSQL databases with minimal locks and minimal efforts.

That would be nice !
```[tasklist]
### Tasks
- [x] add postgres extension (see documentation https://reorg.github.io/pg_repack/)
- [x] PR to update the list of available extensions
- [x] update recommended versions
- [x] update schema
```

**Comment by dbarrosop** [comment]
`{14.13,15.8,16.4}-202401126-1` host just now released with this extension:

https://hub.docker.com/repository/docker/nhost/postgres/general
